"""sqlite timestamp defaults

The init migration was autogenerated against Postgres and baked
``DEFAULT now()`` into the DDL. SQLite has no ``now()`` function, so every
INSERT that relied on the default failed with
``sqlite3.OperationalError: unknown function: now()``.

``CURRENT_TIMESTAMP`` is understood by both SQLite and Postgres.

Revision ID: c9d1a2b3f4e5
Revises: 18940f41430f
Create Date: 2026-07-16 19:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d1a2b3f4e5'
down_revision: Union[str, None] = '18940f41430f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TS_COLUMNS = {
    'subscribers': ['created_at'],
    'users': ['created_at', 'updated_at'],
    'newsletters': ['created_at'],
    'service_requests': ['created_at', 'updated_at'],
    'client_documents': ['created_at'],
    'consultations': ['created_at'],
    'messages': ['created_at'],
}


def _set_default(default: sa.sql.elements.TextClause) -> None:
    for table, cols in TS_COLUMNS.items():
        # batch mode: on SQLite the table is recreated (data preserved),
        # on Postgres this degrades to plain ALTER COLUMN statements.
        with op.batch_alter_table(table) as batch:
            for col in cols:
                batch.alter_column(
                    col,
                    existing_type=sa.DateTime(timezone=True),
                    server_default=default,
                    existing_nullable=True,
                )


def upgrade() -> None:
    """Upgrade schema."""
    _set_default(sa.text('CURRENT_TIMESTAMP'))


def downgrade() -> None:
    """Downgrade schema."""
    _set_default(sa.text('now()'))
